### DISCUSSION TITLE
How do I turn on/off individual outlets?

### DISCUSSION THREAD

**Discussion by dkvdm** [eseglem/hass-wattbox#14] [Q&A]
I might be completely stupid and misreading the documentation, but how do I turn on/off individual outlets rather than the master switch? Thanks!

**Comment by eseglem** [comment]
The docs could definitely use some more work. And some additional work on usability in general. There are entities for each switch plus the master. 

Settings > Devices and Services > Entities > Search 'wattbox outlet'.

<img width="381" alt="Screenshot" src="https://github.com/eseglem/hass-wattbox/assets/5920492/5a846ca3-6e9a-4e0c-a34b-95535194a31c">

Edit: I realized discussions weren't on for this repo, so I turned them on and converted this to a discussion.

**Comment by dkvdm** [comment]
I figured that's where they would be, though unfortunately I don't have any of the entities corresponding to an individual outlet:
![wattbox entities](https://github.com/eseglem/hass-wattbox/assets/456094/ee3c3656-392d-4674-96f2-b5530f26f450)

Model: WB-800-IPVM-12
Firmware: 2.5.0.8

Config:
```yaml
wattbox:
- host: 192.168.1.39
  name: wattbox
  username: redacted
  password: redacted
```

**Comment by eseglem** [comment]
Since you have an 800 series you will need to use the beta version to integrate with it. I am a bit surprised the integration didn't break before adding those entities. Definitely confusing behavior.

HACS > Wattbox > Redownload > Show beta versions > Select the highest version you can (currently v0.9.0b5)

And you will need to add port to the config. The 800s use 22 / 23 for control and got rid of most of the http controls. 

```yaml
wattbox:
- name: wattbox
  host: 192.168.1.39
  port: 22
  username: redacted
  password: redacted
```

Hopefully I can migrate things over to the Config Flow UI at some point and make it easier to deal with the differences in models.
