### ISSUE TITLE
800 Series Not Connecting

### ISSUE THREAD

**Issue by kernelpanic85** [eseglem/hass-wattbox#29]
## Version of the custom_component

Follow up from #21. I downloaded the latest code from the develop branch and I'm still having issues getting the 800 series to connect in HA.

## Configuration
```
wattbox:
- host: 192.168.2.62
  name: Theater-PDU
  port: 22
  username: !secret wattbox_user
  password: !secret wattbox_pw
  scan_interval: 00:00:10
```
```yaml

```
## Describe the bug
 I can successfully SSH from the HA CLI to the Wattbox with the credentials configured and run commands, but the integration still doesn't connect. 

## Debug log

[wattbox logs 1.txt](https://github.com/user-attachments/files/19431918/wattbox.logs.1.txt)

[wattbox logs 2.txt](https://github.com/user-attachments/files/19431920/wattbox.logs.2.txt)

**Comment by eseglem** [comment]
The timeout makes me believe it is a networking issue. I remember having an issue in the past where something was off with the container networking and it was unable to reach out to the wattbox from inside of it. Perhaps the HA CLI network could be different from the network of where the python is running. 

You can try to add this to your `configuration.yaml` and see if anything else shows up. But I doubt there is going to be much new info when it's timing out. 

```yaml
logger:
  logs:
    custom_components.wattbox: debug
    pywattbox: debug
    scrapli: debug
```

If you think the networking is ok, but the wattbox is being extremely slow to respond, you could temporarily edit `/usr/local/lib/python3.13/site-packages/pywattbox/driver/async_driver.py` and change the default timeout(s).

I think I have some fixes for the warnings about blocking calls though. Which should just be warnings and unrelated to the symptoms you are seeing. They'll be up soon.
